import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMissingDomainTables1788391784563 implements MigrationInterface {
    name = 'AddMissingDomainTables1788391784563'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth_attempts" DROP CONSTRAINT "FK_auth_attempts_accountUserId"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_sessions_userId"`);
        await queryRunner.query(`ALTER TABLE "challenges" DROP CONSTRAINT "FK_challenges_accountUserId"`);
        await queryRunner.query(`ALTER TABLE "challenges" DROP CONSTRAINT "FK_challenges_authAttemptId"`);
        await queryRunner.query(`ALTER TABLE "challenges" DROP CONSTRAINT "FK_challenges_sessionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_allowed_email_domains_emailDomain"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_entries_actorId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_entries_targetEntity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_entries_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_auth_attempts_accountUserId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_auth_attempts_occurredAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sessions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sessions_idleExpiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sessions_absoluteExpiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_googleSubjectId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_accountStatus"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_challenges_authAttemptId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_challenges_accountUserId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_challenges_sessionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_challenges_expiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deletion_requests_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deletion_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pending_review_items_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pending_review_items_dueBy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_assignment_rules_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_security_alerts_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_security_alerts_triggeredAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_system_config_key"`);
        await queryRunner.query(`CREATE TABLE "import_row_errors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_batch_id" uuid NOT NULL, "row_number" integer NOT NULL, "field_name" text NOT NULL, "error_reason" text NOT NULL, CONSTRAINT "PK_8a45918af12a5335e72f357268d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "import_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "term" text NOT NULL, "uploaded_by" uuid NOT NULL, "file_name" text NOT NULL, "template_version" text NOT NULL, "content_hash" text NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'validating', "row_count" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applied_at" TIMESTAMP WITH TIME ZONE, "expired_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6162597a2576c03e04bb2c1a2dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cafcaccf1d2d925a8583a9c9b9" ON "import_batches"  ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_26c24e52e5c1c140c163e37752" ON "import_batches"  ("uploaded_by", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a57e73af1cca0fba0dc801ad56" ON "import_batches"  ("term", "created_at") `);
        await queryRunner.query(`CREATE TABLE "dataset_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "term" text NOT NULL, "import_batch_id" uuid NOT NULL, "previous_version_id" uuid, "is_current" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2335c164f3df47dabfe7d0fc6e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93779d99367a2c7eef05f04476" ON "dataset_versions"  ("published_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3523158de45473f557493c90d3" ON "dataset_versions"  ("term", "is_current") `);
        await queryRunner.query(`CREATE TABLE "course_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "group_label" character varying(255) NOT NULL, "professor_raw_name" character varying(255), "is_archived" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_709482ceb797ead04b55e9b1547" UNIQUE ("course_id", "group_label"), CONSTRAINT "PK_9722c03add9ea0dca5c69447398" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "courseCode" character varying(255) NOT NULL, "term" character varying(255) NOT NULL, "title" character varying(255) NOT NULL, "department" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "course_group_id" uuid NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "enrolled_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dropped_at" TIMESTAMP WITH TIME ZONE, "term" character varying(255), CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "professor_teaching_claims" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "professor_id" uuid NOT NULL, "course_group_id" uuid NOT NULL, "claimed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "verified_at" TIMESTAMP WITH TIME ZONE, "released_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b75cc67cb9305cff4cfa1b13f43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answer_votes" ("user_id" uuid NOT NULL, "answer_id" uuid NOT NULL, "value" character varying(16) NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5ede7f08d3726f57100d59b04c1" PRIMARY KEY ("user_id", "answer_id"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question_id" uuid NOT NULL, "author_id" uuid NOT NULL, "body" text NOT NULL, "is_accepted" boolean NOT NULL DEFAULT false, "hidden_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9c32cec6c71e06da0254f2226c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying(255) NOT NULL, CONSTRAINT "UQ_bf8c8eae11adc771af15ea958f9" UNIQUE ("label"), CONSTRAINT "PK_18a3eaf58525b74cc98bbd84419" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question_tags" ("question_id" uuid NOT NULL, "category_tag_id" uuid NOT NULL, CONSTRAINT "PK_8a7415ca6e407a5b1ecf4d4c03b" PRIMARY KEY ("question_id", "category_tag_id"))`);
        await queryRunner.query(`CREATE TABLE "question_votes" ("user_id" uuid NOT NULL, "question_id" uuid NOT NULL, "value" character varying(16) NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b192f4094aec328ef306e5662b6" PRIMARY KEY ("user_id", "question_id"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "author_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'open', "is_locked" boolean NOT NULL DEFAULT false, "hidden_at" TIMESTAMP WITH TIME ZONE, "edit_window_expires_at" TIMESTAMP WITH TIME ZONE, "resolutionNote" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporter_id" uuid, "targetType" character varying(32) NOT NULL, "target_id" uuid NOT NULL, "reason" text NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "course_group_id" uuid NOT NULL, "professor_id" uuid NOT NULL, "body" text NOT NULL, "published_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expiry_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "muted_courses" ("user_id" uuid NOT NULL, "course_id" uuid NOT NULL, CONSTRAINT "PK_dbed636843639f23e68190f95c6" PRIMARY KEY ("user_id", "course_id"))`);
        await queryRunner.query(`CREATE TABLE "notification_delivery_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "notification_id" uuid NOT NULL, "channel" text NOT NULL, "outcome" text NOT NULL, "reason_code" text, "destination_snapshot" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d02cbec99bc30d81d79705caa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("userId" uuid NOT NULL DEFAULT uuid_generate_v4(), "reminders_enabled" boolean NOT NULL DEFAULT true, "announcements_enabled" boolean NOT NULL DEFAULT true, "user_id" uuid, CONSTRAINT "PK_b70c44e8b00757584a393225593" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient_id" uuid NOT NULL, "notification_type" character varying(32) NOT NULL, "official_event_id" uuid, "personal_event_id" uuid, "announcement_id" uuid, "reminder_window" character varying(32), "channel" character varying(32) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'queued', "reason_code" character varying(255), "idempotency_key" text NOT NULL, "triggered_by_notification_id" uuid, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "delivered_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_5af2abaf70226e88b27ae3b6391" UNIQUE ("idempotency_key"), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "method_type" character varying(32) NOT NULL, "value" text NOT NULL, "is_preferred" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_23dba1e45090b3cee8798abce5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "professor_schedule_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "professor_id" uuid NOT NULL, "file_url" character varying(2048), "mime_type" character varying(255), "file_size_bytes" bigint, "uploaded_at" TIMESTAMP WITH TIME ZONE, "office_hours_summary" text, CONSTRAINT "UQ_487a75e764fb4bf5213f4c61b45" UNIQUE ("professor_id"), CONSTRAINT "REL_487a75e764fb4bf5213f4c61b4" UNIQUE ("professor_id"), CONSTRAINT "PK_11d397aa17811ca1649e37f86f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profiles" ("userId" uuid NOT NULL, "photo_url" character varying(255), "verification_status" character varying(32) NOT NULL DEFAULT 'unverified', "created_at" TIMESTAMP WITH TIME ZONE, "user_id" uuid, CONSTRAINT "REL_9e432b7df0d182f8d292902d1a" UNIQUE ("user_id"), CONSTRAINT "PK_315ecd98bd1a42dcf2ec4e2e985" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "visibility_settings" ("user_id" uuid NOT NULL, "field_name" character varying(32) NOT NULL, "visibility_level" character varying(32) NOT NULL, CONSTRAINT "PK_d2ed6f6b25398d0821142fe5f9a" PRIMARY KEY ("user_id", "field_name"))`);
        await queryRunner.query(`CREATE TABLE "official_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dataset_version_id" uuid NOT NULL, "course_group_id" uuid NOT NULL, "eventType" character varying(32) NOT NULL, "start_datetime" TIMESTAMP WITH TIME ZONE NOT NULL, "end_datetime" TIMESTAMP WITH TIME ZONE NOT NULL, "location" character varying(255), CONSTRAINT "PK_340064152d825e7311f21b27780" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "personal_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "startDatetime" TIMESTAMP WITH TIME ZONE NOT NULL, "endDatetime" TIMESTAMP WITH TIME ZONE NOT NULL, "is_recurring" boolean NOT NULL DEFAULT false, "recurrence_rule" text, "recurrence_end_date" TIMESTAMP WITH TIME ZONE, "location" character varying(255), "eventType" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8886c2adccbf466392547dfb1b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "personal_event_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "personal_event_id" uuid NOT NULL, "occurrence_start_datetime" TIMESTAMP WITH TIME ZONE NOT NULL, "is_cancelled" boolean NOT NULL DEFAULT false, "start_datetime" TIMESTAMP WITH TIME ZONE, "end_datetime" TIMESTAMP WITH TIME ZONE, "title" character varying(255), "description" text, "location" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_03dfae46ca6b03befa00a58c973" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_googleSubjectId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "googleSubjectId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "googleSubjectId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_125198c50a52e638b84643bb739" UNIQUE ("googleSubjectId")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fullName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_username"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_studentOrStaffId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "studentOrStaffId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "studentOrStaffId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_0b0f33d48d7a97ee2d3ebbe0e6e" UNIQUE ("studentOrStaffId")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying(255)`);
        await queryRunner.query(`CREATE INDEX "IDX_da3d79ee83f674d9f5fc9cc88d" ON "question_tags"  ("question_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_320472d7234c05e4e7b8b4c1a8" ON "question_tags"  ("category_tag_id") `);
        await queryRunner.query(`ALTER TABLE "import_row_errors" ADD CONSTRAINT "FK_c7c2f330a12710eaf90dfbc316e" FOREIGN KEY ("import_batch_id") REFERENCES "import_batches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_batches" ADD CONSTRAINT "FK_97f6eb90260576d70b5190f39e4" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset_versions" ADD CONSTRAINT "FK_abaf1500512669a0271c6ba2495" FOREIGN KEY ("import_batch_id") REFERENCES "import_batches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset_versions" ADD CONSTRAINT "FK_c72a13f77c9d7196c1d97c06b21" FOREIGN KEY ("previous_version_id") REFERENCES "dataset_versions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "challenges" ADD CONSTRAINT "FK_067a5a5582d7843e4a28e876061" FOREIGN KEY ("authAttemptId") REFERENCES "auth_attempts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "challenges" ADD CONSTRAINT "FK_e225ce650da9b86693729c30777" FOREIGN KEY ("accountUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "challenges" ADD CONSTRAINT "FK_8cca2097f43ac1981b4a35cbb41" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_groups" ADD CONSTRAINT "FK_ca2197cfbf4f699407700aacd04" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_7205f8af9a83667ab82a62fe02d" FOREIGN KEY ("course_group_id") REFERENCES "course_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professor_teaching_claims" ADD CONSTRAINT "FK_60610c364413b2e8ce8152e39d1" FOREIGN KEY ("professor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professor_teaching_claims" ADD CONSTRAINT "FK_a48d1975a0970d47d7bf86b90e4" FOREIGN KEY ("course_group_id") REFERENCES "course_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_votes" ADD CONSTRAINT "FK_ab3699386b605aa8235fde46cc4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_votes" ADD CONSTRAINT "FK_f0157023465e675660fd1709118" FOREIGN KEY ("answer_id") REFERENCES "answers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_677120094cf6d3f12df0b9dc5d3" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_3a1ad37b311f0f3bdda728e507f" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_tags" ADD CONSTRAINT "FK_da3d79ee83f674d9f5fc9cc88d0" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_tags" ADD CONSTRAINT "FK_320472d7234c05e4e7b8b4c1a81" FOREIGN KEY ("category_tag_id") REFERENCES "category_tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_votes" ADD CONSTRAINT "FK_b3fd868c90abc25cab8159c4881" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_votes" ADD CONSTRAINT "FK_c7514956e9a7667e5d0136b2559" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_dcaac7adf4b5af7bc980ec5250e" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_e8f5ed3ae7b8b9e1f18fe9bb150" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_36dd3462be1c9451a3d8369d48c" FOREIGN KEY ("course_group_id") REFERENCES "course_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_44afa99f7ab310fcfaa58777996" FOREIGN KEY ("professor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "muted_courses" ADD CONSTRAINT "FK_402920749770b6d0bebe4399806" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "muted_courses" ADD CONSTRAINT "FK_7e4f987458f30f194c4b16388cc" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_delivery_logs" ADD CONSTRAINT "FK_222d7564d68c0c89c51d7ad4569" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_b5b686e399aea6a919d9b0cc49c" FOREIGN KEY ("official_event_id") REFERENCES "official_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8e8789c6a9590d537374ae882fe" FOREIGN KEY ("personal_event_id") REFERENCES "personal_events"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_f8c344f6b38a337948bd4d7cbc1" FOREIGN KEY ("announcement_id") REFERENCES "announcements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9c2e0fbbe6a0399f5cc4dad0bfc" FOREIGN KEY ("triggered_by_notification_id") REFERENCES "notifications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_methods" ADD CONSTRAINT "FK_42adcbab53de711d5e0678c09bd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professor_schedule_documents" ADD CONSTRAINT "FK_487a75e764fb4bf5213f4c61b45" FOREIGN KEY ("professor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visibility_settings" ADD CONSTRAINT "FK_510e055cf9511310d08d932c48e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "official_events" ADD CONSTRAINT "FK_7c3a362de8a7a3ff1825f5bfa87" FOREIGN KEY ("dataset_version_id") REFERENCES "dataset_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "official_events" ADD CONSTRAINT "FK_2fdf2627d49bb92fd1752172030" FOREIGN KEY ("course_group_id") REFERENCES "course_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_event_exceptions" ADD CONSTRAINT "FK_35cdc7dbe2a77859c50e6e43aed" FOREIGN KEY ("personal_event_id") REFERENCES "personal_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_events" ADD CONSTRAINT "FK_057d9c86865915d1115db22d9a2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "personal_events" DROP CONSTRAINT "FK_057d9c86865915d1115db22d9a2"`);
        await queryRunner.query(`ALTER TABLE "personal_event_exceptions" DROP CONSTRAINT "FK_35cdc7dbe2a77859c50e6e43aed"`);
        await queryRunner.query(`ALTER TABLE "official_events" DROP CONSTRAINT "FK_2fdf2627d49bb92fd1752172030"`);
        await queryRunner.query(`ALTER TABLE "official_events" DROP CONSTRAINT "FK_7c3a362de8a7a3ff1825f5bfa87"`);
        await queryRunner.query(`ALTER TABLE "visibility_settings" DROP CONSTRAINT "FK_510e055cf9511310d08d932c48e"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2"`);
        await queryRunner.query(`ALTER TABLE "professor_schedule_documents" DROP CONSTRAINT "FK_487a75e764fb4bf5213f4c61b45"`);
        await queryRunner.query(`ALTER TABLE "contact_methods" DROP CONSTRAINT "FK_42adcbab53de711d5e0678c09bd"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9c2e0fbbe6a0399f5cc4dad0bfc"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_f8c344f6b38a337948bd4d7cbc1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8e8789c6a9590d537374ae882fe"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_b5b686e399aea6a919d9b0cc49c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "notification_delivery_logs" DROP CONSTRAINT "FK_222d7564d68c0c89c51d7ad4569"`);
        await queryRunner.query(`ALTER TABLE "muted_courses" DROP CONSTRAINT "FK_7e4f987458f30f194c4b16388cc"`);
        await queryRunner.query(`ALTER TABLE "muted_courses" DROP CONSTRAINT "FK_402920749770b6d0bebe4399806"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_44afa99f7ab310fcfaa58777996"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_36dd3462be1c9451a3d8369d48c"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_e8f5ed3ae7b8b9e1f18fe9bb150"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_dcaac7adf4b5af7bc980ec5250e"`);
        await queryRunner.query(`ALTER TABLE "question_votes" DROP CONSTRAINT "FK_c7514956e9a7667e5d0136b2559"`);
        await queryRunner.query(`ALTER TABLE "question_votes" DROP CONSTRAINT "FK_b3fd868c90abc25cab8159c4881"`);
        await queryRunner.query(`ALTER TABLE "question_tags" DROP CONSTRAINT "FK_320472d7234c05e4e7b8b4c1a81"`);
        await queryRunner.query(`ALTER TABLE "question_tags" DROP CONSTRAINT "FK_da3d79ee83f674d9f5fc9cc88d0"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_3a1ad37b311f0f3bdda728e507f"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_677120094cf6d3f12df0b9dc5d3"`);
        await queryRunner.query(`ALTER TABLE "answer_votes" DROP CONSTRAINT "FK_f0157023465e675660fd1709118"`);
        await queryRunner.query(`ALTER TABLE "answer_votes" DROP CONSTRAINT "FK_ab3699386b605aa8235fde46cc4"`);
        await queryRunner.query(`ALTER TABLE "professor_teaching_claims" DROP CONSTRAINT "FK_a48d1975a0970d47d7bf86b90e4"`);
        await queryRunner.query(`ALTER TABLE "professor_teaching_claims" DROP CONSTRAINT "FK_60610c364413b2e8ce8152e39d1"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_7205f8af9a83667ab82a62fe02d"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c"`);
        await queryRunner.query(`ALTER TABLE "course_groups" DROP CONSTRAINT "FK_ca2197cfbf4f699407700aacd04"`);
        await queryRunner.query(`ALTER TABLE "challenges" DROP CONSTRAINT "FK_8cca2097f43ac1981b4a35cbb41"`);
        await queryRunner.query(`ALTER TABLE "challenges" DROP CONSTRAINT "FK_e225ce650da9b86693729c30777"`);
        await queryRunner.query(`ALTER TABLE "challenges" DROP CONSTRAINT "FK_067a5a5582d7843e4a28e876061"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "dataset_versions" DROP CONSTRAINT "FK_c72a13f77c9d7196c1d97c06b21"`);
        await queryRunner.query(`ALTER TABLE "dataset_versions" DROP CONSTRAINT "FK_abaf1500512669a0271c6ba2495"`);
        await queryRunner.query(`ALTER TABLE "import_batches" DROP CONSTRAINT "FK_97f6eb90260576d70b5190f39e4"`);
        await queryRunner.query(`ALTER TABLE "import_row_errors" DROP CONSTRAINT "FK_c7c2f330a12710eaf90dfbc316e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_320472d7234c05e4e7b8b4c1a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da3d79ee83f674d9f5fc9cc88d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_0b0f33d48d7a97ee2d3ebbe0e6e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "studentOrStaffId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "studentOrStaffId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_studentOrStaffId" UNIQUE ("studentOrStaffId")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_username" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fullName" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_125198c50a52e638b84643bb739"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "googleSubjectId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "googleSubjectId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_googleSubjectId" UNIQUE ("googleSubjectId")`);
        await queryRunner.query(`DROP TABLE "personal_events"`);
        await queryRunner.query(`DROP TABLE "personal_event_exceptions"`);
        await queryRunner.query(`DROP TABLE "official_events"`);
        await queryRunner.query(`DROP TABLE "visibility_settings"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TABLE "professor_schedule_documents"`);
        await queryRunner.query(`DROP TABLE "contact_methods"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP TABLE "notification_delivery_logs"`);
        await queryRunner.query(`DROP TABLE "muted_courses"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TABLE "question_votes"`);
        await queryRunner.query(`DROP TABLE "question_tags"`);
        await queryRunner.query(`DROP TABLE "category_tags"`);
        await queryRunner.query(`DROP TABLE "answers"`);
        await queryRunner.query(`DROP TABLE "answer_votes"`);
        await queryRunner.query(`DROP TABLE "professor_teaching_claims"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TABLE "course_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3523158de45473f557493c90d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93779d99367a2c7eef05f04476"`);
        await queryRunner.query(`DROP TABLE "dataset_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a57e73af1cca0fba0dc801ad56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26c24e52e5c1c140c163e37752"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cafcaccf1d2d925a8583a9c9b9"`);
        await queryRunner.query(`DROP TABLE "import_batches"`);
        await queryRunner.query(`DROP TABLE "import_row_errors"`);
        await queryRunner.query(`CREATE INDEX "IDX_system_config_key" ON "system_config" USING btree ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_security_alerts_triggeredAt" ON "security_alerts" USING btree ("triggeredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_security_alerts_userId" ON "security_alerts" USING btree ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_assignment_rules_priority" ON "role_assignment_rules" USING btree ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_pending_review_items_dueBy" ON "pending_review_items" USING btree ("dueBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_pending_review_items_userId" ON "pending_review_items" USING btree ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_deletion_requests_status" ON "deletion_requests" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_deletion_requests_userId" ON "deletion_requests" USING btree ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_challenges_expiresAt" ON "challenges" USING btree ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_challenges_sessionId" ON "challenges" USING btree ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_challenges_accountUserId" ON "challenges" USING btree ("accountUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_challenges_authAttemptId" ON "challenges" USING btree ("authAttemptId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_accountStatus" ON "users" USING btree ("accountStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" USING btree ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_googleSubjectId" ON "users" USING btree ("googleSubjectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_role" ON "users" USING btree ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_sessions_absoluteExpiresAt" ON "sessions" USING btree ("absoluteExpiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_sessions_idleExpiresAt" ON "sessions" USING btree ("idleExpiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_sessions_userId" ON "sessions" USING btree ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_auth_attempts_occurredAt" ON "auth_attempts" USING btree ("occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_auth_attempts_accountUserId" ON "auth_attempts" USING btree ("accountUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_entries_createdAt" ON "audit_log_entries" USING btree ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_entries_targetEntity" ON "audit_log_entries" USING btree ("targetEntity") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_entries_actorId" ON "audit_log_entries" USING btree ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_allowed_email_domains_emailDomain" ON "allowed_email_domains" USING btree ("emailDomain") `);
        await queryRunner.query(`ALTER TABLE "challenges" ADD CONSTRAINT "FK_challenges_sessionId" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "challenges" ADD CONSTRAINT "FK_challenges_authAttemptId" FOREIGN KEY ("authAttemptId") REFERENCES "auth_attempts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "challenges" ADD CONSTRAINT "FK_challenges_accountUserId" FOREIGN KEY ("accountUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_sessions_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_attempts" ADD CONSTRAINT "FK_auth_attempts_accountUserId" FOREIGN KEY ("accountUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
